FROM node:24.13.0-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm i

COPY . .

ENV VUE_APP_ENV=VUE_APP_ENV_VALUE
ENV VUE_APP_PUBLIC_PATH=VUE_APP_PUBLIC_PATH_VALUE
ENV VUE_APP_CONFIG_GEN_API_URL=VUE_APP_CONFIG_GEN_API_URL_VALUE
ENV VUE_APP_PROJECT_GEN_API_URL=VUE_APP_PROJECT_GEN_API_URL_VALUE
ENV VUE_APP_AUTH_URL=VUE_APP_AUTH_URL_VALUE
ENV VUE_APP_CONFIG_GEN_STATUS_URL=VUE_APP_CONFIG_GEN_STATUS_URL_VALUE
ENV VUE_APP_PROJECT_GEN_STATUS_URL=VUE_APP_PROJECT_GEN_STATUS_URL_VALUE
ENV VUE_APP_APIGEN_DOTNET_URL=VUE_APP_APIGEN_DOTNET_URL_VALUE
ENV VUE_APP_APIGEN_SPRINGBOOT_URL=VUE_APP_APIGEN_SPRINGBOOT_URL_VALUE
ENV VUE_APP_APIGEN_PYTHON_URL=VVUE_APP_APIGEN_PYTHON_URL_VALUE
ENV VUE_APP_DB_EXPLORER_URL=VUE_APP_DB_EXPLORER_URL_VALUE
ENV VUE_APP_API_KEY=VUE_APP_API_KEY_VALUE
ENV VUE_APP_WSO2_STATUS_URL=VUE_APP_WSO2_STATUS_URL_VALUE

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]