import { EntityStoreObject } from '@/store/entities/state';
import {
  EntityAttributeStoreObject,
  Column,
  Relation,
  Validation,
} from '@/store/entity-attributes/state';
import {
  ApigenModel,
  ApigenModelAttribute,
  ApigenModelAttributeRelationalPersistence,
  ApigenModelAttributeValidation,
} from '../models/apigen.types';

function buildRelationalPersistence(
  column: Column | undefined,
  relation: Relation | undefined,
): ApigenModelAttributeRelationalPersistence {
  const rp: ApigenModelAttributeRelationalPersistence = {};

  if (relation) {
    if (relation.type === 'MANY_TO_ONE' || relation.type === 'ONE_TO_ONE') {
      if (column?.name) {
        rp.column = column.name;
      }
    } else if (relation.type === 'ONE_TO_MANY') {
      // FK is on the "many" side — look it up from the corresponding ManyToOne
      // ownerEntityName is passed via closure workaround (see buildModelAttribute)
    } else if (relation.type === 'MANY_TO_MANY') {
      if (relation.intermediate_table) {
        rp['join-table'] = relation.intermediate_table;
      }
      if (relation.columns && Array.isArray(relation.columns) && relation.columns.length >= 2) {
        rp['join-column'] = relation.columns[0].name || '';
        rp['inverse-join-column'] = relation.columns[1].name || '';
      }
    }
  } else if (column) {
    if (column.primary_key) {
      rp['primary-key'] = true;
      rp.autogenerated = true;
    }
    if (column.unique) rp.unique = true;
    if (column.sequence_name) rp.sequence = column.sequence_name;
  }

  return rp;
}

function buildValidations(validations: Validation[] | undefined): ApigenModelAttributeValidation[] | undefined {
  if (!validations || validations.length === 0) return undefined;

  return validations.map((v) => {
    const validation: ApigenModelAttributeValidation = {
      type: v.type,
    };
    if (v.value !== undefined) {
      const numValue = Number(v.value);
      if (!Number.isNaN(numValue) && (v.type === 'Size' || v.type === 'MaxLength')) {
        validation.max = numValue;
      } else {
        validation.value = v.value;
      }
    }
    return validation;
  });
}

function buildModelAttribute(
  attr: EntityAttributeStoreObject,
  entityToSchema: Map<string, string>,
  ownerEntityName: string,
  oneToManyFKMap: Map<string, string>,
  relationNameOverrides?: Map<string, string>,
): ApigenModelAttribute {
  // For relations, use OpenAPI property name if available (overrides DB attr name)
  const attrName = (relationNameOverrides && attr.relation)
    ? (relationNameOverrides.get(attr.name) || attr.name)
    : attr.name;

  const modelAttr: ApigenModelAttribute = {
    name: attrName,
    type: attr.type,
  };

  if (attr.relation) {
    const { relation } = attr;
    const foreignModel = entityToSchema.get(relation.foreign_class) || relation.foreign_class;

    if (relation.type === 'MANY_TO_ONE' || relation.type === 'ONE_TO_ONE') {
      modelAttr.type = foreignModel;
      const rp = buildRelationalPersistence(attr.column, relation);
      if (Object.keys(rp).length > 0) {
        modelAttr['relational-persistence'] = rp;
      }
    } else if (relation.type === 'ONE_TO_MANY') {
      modelAttr.type = 'Array';
      modelAttr['items-type'] = foreignModel;
      const fkCol = oneToManyFKMap.get(`${ownerEntityName}→${relation.foreign_class}`);
      if (fkCol) {
        modelAttr['relational-persistence'] = { 'foreign-column': fkCol };
      }
    } else if (relation.type === 'MANY_TO_MANY') {
      modelAttr.type = 'Array';
      modelAttr['items-type'] = foreignModel;
      const rp = buildRelationalPersistence(attr.column, relation);
      if (Object.keys(rp).length > 0) {
        modelAttr['relational-persistence'] = rp;
      }
    }
  } else {
    if (attr.type === 'array' && attr.type_of_array) {
      modelAttr.type = 'Array';
      modelAttr['items-type'] = attr.type_of_array;
    }

    const rp = buildRelationalPersistence(attr.column, undefined);
    if (Object.keys(rp).length > 0) {
      modelAttr['relational-persistence'] = rp;
    }

    const validations = buildValidations(attr.validations);
    if (validations) {
      modelAttr.validations = validations;
    }
  }

  return modelAttr;
}

function buildOneToManyFKMap(
  entities: Record<string, EntityStoreObject>,
  entityAttributes: Record<string, EntityAttributeStoreObject>,
): Map<string, string> {
  // key: `${foreignClass}→${ownerClass}` → FK column name on the foreign (many) side
  const map = new Map<string, string>();
  Object.values(entities).forEach((entity) => {
    if (!entity.attributes) return;
    (entity.attributes as any[]).forEach((attrKey) => {
      const attr = typeof attrKey === 'string' ? entityAttributes[attrKey] : attrKey;
      if (!attr?.relation) return;
      if (
        (attr.relation.type === 'MANY_TO_ONE' || attr.relation.type === 'ONE_TO_ONE')
        && attr.column?.name
      ) {
        map.set(`${attr.relation.foreign_class}→${entity.name}`, attr.column.name);
      }
    });
  });
  return map;
}

export default function generateApigenModels(
  entities: Record<string, EntityStoreObject>,
  entityAttributes: Record<string, EntityAttributeStoreObject>,
  entityToSchema: Map<string, string>,
  allRelationNameOverrides?: Map<string, Map<string, string>>,
): Record<string, ApigenModel> {
  const models: Record<string, ApigenModel> = {};
  const oneToManyFKMap = buildOneToManyFKMap(entities, entityAttributes);

  Object.values(entities).forEach((entity) => {
    if (!entity.name) return;
    // Solo generar modelos para entidades que tienen un schema en el OpenAPI
    if (!entityToSchema.has(entity.name)) return;

    const entityOverrides = allRelationNameOverrides?.get(entity.name);
    const attributes: ApigenModelAttribute[] = [];

    if (entity.attributes) {
      (entity.attributes as any[]).forEach((attrKey: any) => {
        const attr = typeof attrKey === 'string' ? entityAttributes[attrKey] : attrKey;
        if (!attr || !attr.name) return;
        attributes.push(buildModelAttribute(attr, entityToSchema, entity.name, oneToManyFKMap, entityOverrides));
      });
    }

    // Usar schema name como clave si existe (Pets → Pet), sino entity name
    const modelKey = entityToSchema.get(entity.name) || entity.name;

    const model: ApigenModel = { attributes };
    if (entity.table && entity.table !== entity.name) {
      model['relational-persistence'] = { table: entity.table };
    }

    models[modelKey] = model;
  });

  return models;
}
